server:
  port: 8082 #设置端口号
spring:
  application:
    name: Customer #设置nacos服务名
  cloud:
    nacos:
      discovery:
        server-addr: 10.8.154.63:8848   #nacos注册中心地址
  main:
    allow-bean-definition-overriding: true