server:
  port: 8081 #设置端口号
spring:
  application:
    name: Prodiver #设置nacos服务名
  cloud:
    nacos:
      discovery:
        server-addr: 10.8.154.63:8848  #nacos注册中心地址
  datasource:
    url: jdbc:mysql://localhost:3306/school?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource